We can write notebooks using a couple different IDEs, popular being 

1. [jupyter](https://jupyter.org/install) which is a bit more advanced and requires installing [anaconda](https://www.anaconda.com/)

2. [rstudio](https://rstudio.com/products/rstudio/)

either can be used to write code in [R](https://www.r-project.org/)

In [2]:
print('hello world')

[1] "hello world"


We can use R as a calculator

In [3]:
1+1

[1] 2

In [4]:
1+2*5

[1] 11

there are also some built-in constants in R

In [5]:
pi
exp(1)

[1] 3.141593

[1] 2.718282

there are also special infinite values

In [7]:
1/0
-1/0

[1] Inf

[1] -Inf

In [8]:
0/0

[1] NaN

to denote nothing we have

In [9]:
NULL

NULL

to denote a missing value

In [10]:
NA

[1] NA

# Variable assignment and simple objects

In [13]:
x = 1
y <- 2
3 -> z
x;y;z
print(x)

[1] 1

[1] 2

[1] 3

[1] 1


# Vectors

In [19]:
x = c(5,3,7)
x

[1] 5 3 7

In [23]:
x[1]

[1] 5

In [26]:
x[c(-1,-2)]

[1] 7

we can make a vector out of anything

In [27]:
truths <- c(TRUE, FALSE, TRUE)

In [28]:
x[truths]

[1] 5 7

we can make a matrix using the ``matrix`` function

In [30]:
1:25
X <- matrix(1:25,nrow=5,byrow=TRUE)
X

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [31]:
Y <- array(25:49,c(5,5))
Y

[,1] [,2] [,3] [,4] [,5]
[1,] 25   30   35   40   45  
[2,] 26   31   36   41   46  
[3,] 27   32   37   42   47  
[4,] 28   33   38   43   48  
[5,] 29   34   39   44   49

matrix multiplication is done with the operator ``%*%``

In [33]:
X %*% Y

[,1] [,2] [,3] [,4] [,5]
[1,]  415  490  565  640  715
[2,] 1090 1290 1490 1690 1890
[3,] 1765 2090 2415 2740 3065
[4,] 2440 2890 3340 3790 4240
[5,] 3115 3690 4265 4840 5415

# Flow Control

In [35]:
A = FALSE
if(A){
    print("TRUE")
} else{
    print("FALSE")
}

[1] "FALSE"


In [36]:
for(i in 1:10){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [37]:
i = 1
while( i <= 10){
    print(i)
    i = i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


there is a good tutorial by Dr. Leemis [here](http://www.math.wm.edu/~leemis/r.pdf)